## Numpy
- Efficient use of time and memory

In [2]:
import numpy as np
np.__version__

'1.16.5'

In [5]:
a = np.array([1,2,3])
a.ndim

1

In [9]:
b = np.array([[1,2,3],[4,5,6],[8,9,3]])
b.ndim

2

In [10]:
a=np.array([[1,2,3],[4,5,6],[8,9,3]])
print(type(a)) # type of 'a'
print(a.shape) # shape of the array rows & columns
print(a.ndim)# no.of dimensions
print(a.dtype)#  data type of elements in array
print(a.itemsize) # size of each element size in bytes
print(a.size) # no.of elemetns

<class 'numpy.ndarray'>
(3, 3)
2
int32
4
9


In [11]:
a=np.array([[1,2,3],[4,5,6],[8,9,10]],dtype=np.int64)
a.dtype
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10]], dtype=int64)

In [12]:
a2=np.array([12,3.4,56.0])
a2.dtype

dtype('float64')

In [5]:
help(np.array)
help(np)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [19]:
np.array(range(9))   #Arrange the elements in range

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
print(np.arange(10,20,2))

[10 12 14 16 18]


In [21]:
print(np.arange(5))
print(np.arange(4,10,2))
print(np.arange(20,4,-2))
print(np.arange(3,4,0.2))
print(np.arange(2.5,10,0.75))

[0 1 2 3 4]
[4 6 8]
[20 18 16 14 12 10  8  6]
[3.  3.2 3.4 3.6 3.8]
[2.5  3.25 4.   4.75 5.5  6.25 7.   7.75 8.5  9.25]


In [23]:
print(np.linspace(1,10,10))
print(np.linspace(1,10,5)) # both lw,up ar inclusive and equally size elements

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.    3.25  5.5   7.75 10.  ]


In [24]:
print(np.linspace(1,10,4)) # slicing the range with 3rd argument

[ 1.  4.  7. 10.]


#### Array Initialization

In [6]:
import numpy as np
np.ones((5,2),dtype = int)# () represents the shape of array

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [26]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
o=np.ones((3,5,4))
print(o)
print(o.ndim)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
3


In [29]:
np.full((3,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [31]:
print(a)
np.diag(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]]


array([ 1,  5, 10], dtype=int64)

In [41]:
np.eye(3)# Identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
print(np.diag([5,6,7]))
print(np.diag([3,4,5,6]))

[[5 0 0]
 [0 6 0]
 [0 0 7]]
[[3 0 0 0]
 [0 4 0 0]
 [0 0 5 0]
 [0 0 0 6]]


In [64]:
np.diag(a)

array([ 1,  5, 10])

#### Random
- random.randint()
- random.random(())
- random.rand()
- random.randn()

In [44]:
import numpy as np
print(np.random.randint(10))
print(np.random.randint(3,15))
print(np.random.randint(10,100,(2,3)))
print()
# Generating random values in array of size 2*3

9
9
[[59 92 38]
 [33 17 97]]



In [45]:
print(np.random.randint(10,100,(4,2,3)))
# generates random no.s

[[[94 76 32]
  [87 59 25]]

 [[13 16 53]
  [25 74 62]]

 [[17 53 93]
  [25 94 29]]

 [[33 63 80]
  [17 63 82]]]


In [10]:
print(np.random.rand(2,4)) # generates random matrix
print('-------------------')
print(np.random.randn(2,4)) # Both Positive and Negative

[[0.28268648 0.28976004 0.59364693 0.0027902 ]
 [0.04400588 0.63519065 0.14423082 0.71127951]]
-------------------
[[ 1.14479812  0.32019875 -2.00793066 -0.58947652]
 [-0.7972398   0.36995052  0.4232273  -0.13323806]]


In [8]:
np.random.randn(1,2) # random matrix with _ve no.s

array([[ 1.30125929, -0.39794673]])

In [12]:
np.random.normal() # normalizing the random no.s

1.0957300422915994

In [53]:
np.random.randn(3,4) 

array([[-0.65164641,  0.04777914,  0.15792913, -1.0258898 ],
       [-0.14068022, -0.3308338 ,  0.348871  , -0.10241872],
       [ 0.98806054, -0.8917977 , -1.45128781, -0.29751276]])

##### Indexing Slicing and Subsetiing

In [14]:
a=np.random.randint(10,100,(4,4))
a

array([[33, 15, 48, 30],
       [64, 41, 61, 68],
       [37, 56, 57, 62],
       [68, 77, 90, 32]])

In [60]:
s = "kits College"
s[2:4]

'ts'

In [15]:
a[2:4,2:4]


array([[57, 62],
       [90, 32]])

In [16]:
a[2][2]

57

In [66]:
a[1:3]

array([[21, 72, 22, 83],
       [78, 25, 31, 46]])

In [30]:
a[1:3,1:]

array([[76, 72, 67],
       [16, 35, 91]])

In [31]:
a[1:,:3]

array([[22, 76, 72],
       [84, 16, 35],
       [45, 95, 36]])

In [67]:
a3=np.arange(25)
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
a

array([[15, 76, 27, 19],
       [22, 76, 72, 67],
       [84, 16, 35, 91],
       [45, 95, 36, 93]])

In [35]:
a[1:3,1:3]

array([[76, 72],
       [16, 35]])

In [68]:
a>40

array([[ True,  True, False,  True],
       [False,  True, False,  True],
       [ True, False, False,  True],
       [False,  True, False, False]])

In [69]:
a[a>40]

array([45, 47, 57, 72, 83, 78, 46, 61])

In [70]:
a2=np.random.randint(20,200,(6,5))
print(a2)
print("........")
print(a2[1:5:2]) 

[[193 135 176 129  45]
 [ 76 180  40 169 112]
 [ 64  65  50  37 106]
 [ 54 147 132  31  49]
 [ 55  22 100 189 155]
 [187 101  81  95  97]]
........
[[ 76 180  40 169 112]
 [ 54 147 132  31  49]]


In [72]:
a2=np.random.randint(10,25,(5,3))
print(a2)
print("........")
print(a2[1:5:3])

[[24 10 18]
 [18 18 14]
 [20 11 20]
 [18 11 21]
 [22 14 13]]
........
[[18 18 14]
 [22 14 13]]


In [20]:
a4=np.arange(20).reshape(4,5)
print(a4)
print('......')
a5=np.arange(32).reshape(8,4)
print(a5)
print('......')
a6=np.arange(30).reshape(6,-1)
print(a6)
print('........')
a7=np.arange(484).reshape(44,-1)
print(a7)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
......
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
......
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
........
[[  0   1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20  21]
 [ 22  23  24  25  26  27  28  29  30  31  32]
 [ 33  34  35  36  37  38  39  40  41  42  43]
 [ 44  45  46  47  48  49  50  51  52  53  54]
 [ 55  56  57  58  59  60  61  62  63  64  65]
 [ 66  67  68  69  70  71  72  73  74  75  76]
 [ 77  78  79  80  81  82  83  84  85  86  87]
 [ 88  89  90  91  92  93  94  95  96  97  98]
 [ 99 100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119 120]
 [121 122 123 124 125 126 127 128 129 130 131]
 [132 133 134 135 136 137 138 139 140 141 142]
 [143 144 145 146 147 148 149 150 151 152 153]
 [154 155 156 15

In [45]:
print(a4)
a4[1:]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [46]:
a4[2,4] # 3rd row 5th element

14

In [116]:
a4[1:4:2] # 2nd and 4th rows

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19]])

In [49]:
print(a4[2][3]) # (3rd row and 4th element)

13


In [50]:
a4[2:,:3]

array([[10, 11, 12],
       [15, 16, 17]])

In [51]:
a4[2:,3:]

array([[13, 14],
       [18, 19]])

In [52]:
a4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [124]:
a4[1:5:2,1:5:2]

array([[ 6,  8],
       [16, 18]])

In [125]:
a4[[1,2],[3,4]] # [1,2],[3,4]==(1,3),(2,4)

array([ 8, 14])

In [126]:
a4[1:3,3:5]

array([[ 8,  9],
       [13, 14]])

In [21]:
a2=np.arange(8).reshape(2,2,2)
print(a2)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [22]:
for array in a2:
    print(array)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


### Fancy Indexing

In [24]:
x=np.array([[34,56,12],[34,98,56]])
print(x)

[[34 56 12]
 [34 98 56]]


In [25]:
x>50

array([[False,  True, False],
       [False,  True,  True]])

In [26]:
(x>50).sum()  #Gives Count

3

In [26]:
x[x>50]    # Elements

array([56, 98, 56])

In [27]:
x[(x>50)&(x<80)]=4   # Replace
print(x)

[[34  4 12]
 [34 98  4]]


###  Stacking
- hstack ->horizontal stack
- vstack -> vertical stack

In [27]:
b1=np.random.randint(1,10,(2,2))
b2=np.random.randint(1,10,(2))
print(b1)
print('.......')
print(b2)
np.random.randint(1,10,(2,2))
np.vstack((b1,b2))


[[3 6]
 [8 5]]
.......
[8 5]


array([[3, 6],
       [8, 5],
       [8, 5]])

In [28]:
help(np.hstack)

Help on function hstack in module numpy:

hstack(tup)
    Stack arrays in sequence horizontally (column wise).
    
    This is equivalent to concatenation along the second axis, except for 1-D
    arrays where it concatenates along the first axis. Rebuilds arrays divided
    by `hsplit`.
    
    This function makes most sense for arrays with up to 3 dimensions. For
    instance, for pixel-data with a height (first axis), width (second axis),
    and r/g/b channels (third axis). The functions `concatenate`, `stack` and
    `block` provide more general stacking and concatenation operations.
    
    Parameters
    ----------
    tup : sequence of ndarrays
        The arrays must have the same shape along all but the second axis,
        except 1-D arrays which can be any length.
    
    Returns
    -------
    stacked : ndarray
        The array formed by stacking the given arrays.
    
    See Also
    --------
    stack : Join a sequence of arrays along a new axis.
    vstack : Stac

In [63]:
b3=np.random.randint(1,10,(2,1))
print(b3)
print(b1)
np.hstack((b1,b3))

[[5]
 [6]]
[[5 9]
 [9 8]]


array([[5, 9, 5],
       [9, 8, 6]])

#### Array Manipulation
- Reshape
- Resize
- Flatten
- Expand-dim
- ravel

In [142]:
np.arange(32).reshape(4,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [143]:
np.arange(32).reshape(2,16)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]])

In [64]:
np.arange(32).reshape(32,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31]])

In [146]:
np.arange(32).reshape(4,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31]]])

In [148]:
np.arange(32).reshape(2,4,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]]])

In [151]:
np.arange(32).reshape(8,-1) 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [152]:
np.arange(32).reshape(-1,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [157]:
np.random.randint(1,100,(4,6)).reshape(-1)

array([81, 67, 84, 79, 62, 61, 63,  8, 90, 40, 39, 49, 24, 63, 24,  6, 88,
       29, 69, 18, 51, 62, 96, 52])

In [158]:
np.random.randint(1,100,(4,3)).reshape(12)

array([30, 86, 68, 37, 29, 71, 16, 26,  8, 62,  7, 93])

In [85]:
n = np.random.randint(1,100,(4,2,2))
n

In [81]:
f = np.random.randint(1,100,(4,2,2)).flatten()
f

array([62, 70, 33, 52, 31, 73, 77, 54,  2, 56, 88, 43, 27, 41, 50, 89])

In [ ]:
# Create (5,2)  array ranging from 100 to 200, each 
# element difference is 10


In [92]:
np.arange(100,200,10).reshape(5,2)

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

In [87]:
print(n)
f.reshape(8,2)

[[[ 9 16]
  [28 15]]

 [[ 8 17]
  [13 96]]

 [[59 17]
  [98 12]]

 [[85  4]
  [58 72]]]


array([[62, 70],
       [33, 52],
       [31, 73],
       [77, 54],
       [ 2, 56],
       [88, 43],
       [27, 41],
       [50, 89]])

In [29]:
print(a)
print(a.ndim)
t = np.expand_dims(a,axis=0)
print(t.ndim)
print(t)
print(np.expand_dims(a,axis=1))
print("=======")
print(np.expand_dims(a,axis=2))

[[33 15 48 30]
 [64 41 61 68]
 [37 56 57 62]
 [68 77 90 32]]
2
3
[[[33 15 48 30]
  [64 41 61 68]
  [37 56 57 62]
  [68 77 90 32]]]
[[[33 15 48 30]]

 [[64 41 61 68]]

 [[37 56 57 62]]

 [[68 77 90 32]]]
[[[33]
  [15]
  [48]
  [30]]

 [[64]
  [41]
  [61]
  [68]]

 [[37]
  [56]
  [57]
  [62]]

 [[68]
  [77]
  [90]
  [32]]]


#### Mathematical Operations

In [84]:
a=np.array([1,2,3])
b=np.array([3,5,7])
a+b

array([ 4,  7, 10])

In [30]:
li=[1,2,3]
li2=[4,5,6]
ar=np.array(li)
ar2=np.array(li2)
print(ar)
print(ar2)
print(ar+ar2)
print(ar*ar2)
print(ar/ar2)
print(ar//2)


[1 2 3]
[4 5 6]
[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0 1 1]


[1 2 3]
[4 5 6]
[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0 1 1]


In [89]:
print(ar+5)
print('.....')
print(ar)# braodcasting-> 1 scalar on different object

[6 7 8]
.....
[1 2 3]


In [95]:
ar3=np.full((3,4),2)
ar4=np.full((2,3,1),3)
ar3+ar4

array([[[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]],

       [[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]]])

In [96]:
ar5=np.arange(12).reshape(3,4)
ar6=np.full((2,1,4),2)
print("ar5 array ....\n",ar5)
print("ar6...\n",ar6)
ar5+ar6

ar5 array ....
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
ar6...
 [[[2 2 2 2]]

 [[2 2 2 2]]]


array([[[ 2,  3,  4,  5],
        [ 6,  7,  8,  9],
        [10, 11, 12, 13]],

       [[ 2,  3,  4,  5],
        [ 6,  7,  8,  9],
        [10, 11, 12, 13]]])

In [301]:
m=np.arange(12).reshape(3,4)
m2=np.array([10,20,30,40,50,60,70,80]).reshape(2,1,4)
print(m)
print()
print("printing 2 arrays with 1 row and 4 columns....\n",m2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

printing 2 arrays with 1 row and 4 columns....
 [[[10 20 30 40]]

 [[50 60 70 80]]]


In [186]:
m+m2

array([[[10, 21, 32, 43],
        [14, 25, 36, 47],
        [18, 29, 40, 51]],

       [[50, 61, 72, 83],
        [54, 65, 76, 87],
        [58, 69, 80, 91]]])

In [191]:
m3=np.full((3,4),6)
m4=np.full((2,4,3),3)
m3+m4

ValueError: operands could not be broadcast together with shapes (3,4) (2,4,3) 

In [192]:
np.mean([10,20,30,40])

25.0

In [32]:
matrix=np.array([40,50,60,20,40])
print(np.mean(matrix))
print(matrix.mean())
print(matrix.min())
print(matrix.max())
print(np.median(matrix))

42.0
42.0
20
60
40.0


In [104]:
print(a)
print(np.quantile(a,0.5)) # median Q1
print(np.quantile(a,0.25)) #Median of first half Q1
print(np.quantile(a,0.75)) # Median of 2nd half Q3

[[45 47 40 57]
 [21 72 22 83]
 [78 25 31 46]
 [10 61 38 18]]
42.5
24.25
58.0


#### Logarithms and exponentials

In [105]:
np.log(5)

1.6094379124341003

In [91]:
np.log(0)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


-inf

In [202]:
np.log(1)

0.0

In [203]:
np.log(10)

2.302585092994046

In [106]:
np.log2(2)

1.0

In [100]:
np.log(5)

1.6094379124341003

In [107]:
import math
math.log(5)

1.6094379124341003

In [109]:
math.log(2)

0.6931471805599453

In [110]:
np.log([2,3,4])

array([0.69314718, 1.09861229, 1.38629436])

In [102]:
np.log2([2,3,4])

array([1.       , 1.5849625, 2.       ])

In [303]:
np.log(1),np.log(0),np.log(2)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


(0.0, -inf, 0.6931471805599453)

In [40]:
np.log(2)

0.6931471805599453

In [35]:
np.log1p(1)

0.6931471805599453

In [38]:
np.log1p([2,3,4])

array([1.09861229, 1.38629436, 1.60943791])

In [212]:
np.log(np.exp(1))

1.0

In [213]:
np.exp2(2)

4.0

In [215]:
np.expm1(2)

6.38905609893065

In [113]:
np.exp(1)-1

1.718281828459045

In [106]:
np.exp(5)-1

147.4131591025766

In [218]:
np.exp(2)-1

6.38905609893065

In [109]:
greater([2,3,45],[98,34,2])

[98, 34, 2]

In [ ]:
a=[[1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
  [13,14,15,16]]
   
   o/p:[[2,4],
       [10,12]]
      

In [ ]:
a1=[1,2,3,4]
a2=[2,3,4,5]
result=a1+a2
[9,25,49,81](square of result)

array([[3., 0.],
       [0., 2.]])